### ISSUE TITLE
1.0.0 Release Roadmap

### ISSUE THREAD

**Issue by askvortsov1** [OTA-Insight/djangosaml2idp#34]
# Djangosaml2idp Roadmap

Considering the quantity of modifications that @peppelinux and I have been adding to this project, we thought it would be a good idea to put together a formal roadmap documenting what we've done so far, and what we would like to include for release.

## Main Ideas
* Code Readability and Quality
* Comprehensive Test Coverage
* New Features
* Security
* Assorted Bugfixes
* CI/CD and Release Logistics

## Code Readability and Quality
- [ ] Minimizing Repetition (DRY)
- [ ] Code Style Enforcement
- [ ] Comprehensive Documentation
- [ ] Improved Debug Logging

## Comprehensive Test Coverage
- [ ] Tests for utils
- [ ] Tests with a simulated SAMLRequest
- [ ] Other Tests

## New Features
- [ ] User Agreement Screen
- [ ] Override global configs per-SP
- [ ] SLO Support
- [ ] Better Error Handling

## Security
- [ ] Check signature validation for incoming SAMLRequests

## Assorted Bugfixes
- [ ] Assorted Bugfixes

## CI/CD and Release Logistics
- [ ] Do we want to add bots for code coverage/etc?

**Comment by peppelinux** [comment]
I agree it all, 
we could have the 1.0.0-rc without code coverage and get a roughly the 90% of coverage for final 1.0.0 release. In other words we should close all the issues to get the 1.0.0 release. Excuse me if a I put the last one, about the configurable enc/digest algs but it is very simple to implement... We already have the solution that could have been a mess go without it!

https://github.com/OTA-Insight/djangosaml2idp/issues/35

Other important points:

- we must decide how to manage the branch in relation to goals. We could decide to:
  - have master branch only for release or release candidate
  - have development branch to merge commits and third-party PR from branch related to issues or additional features. In the development branch we should have the ROADMAP.md file with a schema as @askvortsov1 previously wrote

**Comment by askvortsov1** [comment]
Here's my proposal for how to proceed.
1. I commit and push the bugfixes I caught for the errors I introduced a while back. This will make my fork of the master branch (the most up to date version of this repo) usable
2. I create a new "dev" branch, and redirect your PR to that. That becomes our development branch. I set up ROADMAP.md and etc there are you mentioned
3. When ready to release, we PR from dev to master, review, and merge.

@peppelinux Is this approach what you're thinking of?

**Comment by peppelinux** [comment]
I'll do the same.
`git checkout -b dev` :)
then we'll move as we mentioned for branch and whatever already said

**Comment by peppelinux** [comment]
Most of the previous checkpoint was developed in this:
https://github.com/OTA-Insight/djangosaml2idp/pull/39

**Comment by Amertz08** [comment]
I am willing to help get tests sorted out. How up to date are the tests because I ran them and I am getting 15 failures. Are the tests just out of date?

```
_________________________________________________________ TestIdPHandlerViewMixin.test_render_response_constructs_request_session_properly __________________________________________________________

self = <tests.test_views.TestIdPHandlerViewMixin object at 0x10b918ba8>

    @pytest.mark.django_db
    def test_render_response_constructs_request_session_properly(self):
>       (mixin, request, html_response) = self.compile_data_for_render_response()

tests/test_views.py:332: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <tests.test_views.TestIdPHandlerViewMixin object at 0x10b918ba8>

    def compile_data_for_render_response(self):
        mixin = IdPHandlerViewMixin()
>       mixin.set_sp("test_generic_sp")
E       AttributeError: 'IdPHandlerViewMixin' object has no attribute 'set_sp'

tests/test_views.py:300: AttributeError
__________________________________________________________________ TestIdPHandlerViewMixin.test_redirects_multifactor_if_relevant ___________________________________________________________________

self = <tests.test_views.TestIdPHandlerViewMixin object at 0x10b9184e0>

    @pytest.mark.django_db
    def test_redirects_multifactor_if_relevant(self):
>       (mixin, request, html_response) = self.compile_data_for_render_response()

tests/test_views.py:352: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <tests.test_views.TestIdPHandlerViewMixin object at 0x10b9184e0>

    def compile_data_for_render_response(self):
        mixin = IdPHandlerViewMixin()
>       mixin.set_sp("test_generic_sp")
E       AttributeError: 'IdPHandlerViewMixin' object has no attribute 'set_sp'

tests/test_views.py:300: AttributeError
__________________________________________________________________ TestBaseProcessor.test_extract_user_id_configure_by_user_class ___________________________________________________________________

self = <tests.test_processor.TestBaseProcessor object at 0x10bece588>

    def test_extract_user_id_configure_by_user_class(self):
    
        user = User()
        user.USERNAME_FIELD = 'email'
        user.email = 'test_email'
    
>       assert BaseProcessor('entity-id').get_user_id(user) == 'test_email'
E       TypeError: get_user_id() missing 2 required positional arguments: 'sp' and 'idp_config'

tests/test_processor.py:27: TypeError
___________________________________________________________________ TestBaseProcessor.test_extract_user_id_configure_by_settings ____________________________________________________________________

self = <tests.test_processor.TestBaseProcessor object at 0x10bec7ef0>, settings = <pytest_django.fixtures.SettingsWrapper object at 0x10bec7550>

    def test_extract_user_id_configure_by_settings(self, settings):
        """Should use `settings.SAML_IDP_DJANGO_USERNAME_FIELD` to determine the user id field"""
    
        settings.SAML_IDP_DJANGO_USERNAME_FIELD = 'first_name'
    
        user = User()
        user.first_name = 'test_first_name'
    
>       assert BaseProcessor('entity-id').get_user_id(user) == 'test_first_name'
E       TypeError: get_user_id() missing 2 required positional arguments: 'sp' and 'idp_config'

tests/test_processor.py:37: TypeError
_______________________________________________________________________ TestBaseProcessor.test_extract_user_id_from_sp_config _______________________________________________________________________

self = <tests.test_processor.TestBaseProcessor object at 0x10b903080>

    def test_extract_user_id_from_sp_config(self):
    
        user = User()
        user.special_id = 'test_special_id'
    
        sp_config = {
            'nameid_field': 'special_id'
        }
    
>       assert BaseProcessor('entity_id').get_user_id(user, sp_config) == 'test_special_id'
E       TypeError: get_user_id() missing 1 required positional argument: 'idp_config'

tests/test_processor.py:48: TypeError
__________________________________________________________________ TestBaseProcessor.test_extract_user_id_from_sp_config_if_method __________________________________________________________________

self = <tests.test_processor.TestBaseProcessor object at 0x10bebb978>

    def test_extract_user_id_from_sp_config_if_method(self):
    
        def random_method(self):
            return "test method result"
    
        User.random_method = random_method
    
        user = User()
        sp_config = {
            'nameid_field': 'random_method'
        }
    
>       assert BaseProcessor('entity_id').get_user_id(user, sp_config) == 'test method result'
E       TypeError: get_user_id() missing 1 required positional argument: 'idp_config'

tests/test_processor.py:62: TypeError
_________________________________________________________________ TestSSOEntry.test_sso_entry_returns_bad_request_if_no_samlrequest _________________________________________________________________

self = <tests.test_views.TestSSOEntry object at 0x10bebe2b0>

    def test_sso_entry_returns_bad_request_if_no_samlrequest(self):
        del sample_get_request.GET['SAMLRequest']
    
        response = sso_entry(sample_get_request)
    
>       assert isinstance(response, HttpResponseBadRequest)
E       assert False
E        +  where False = isinstance(<TemplateResponse status_code=400, "text/html; charset=utf-8">, HttpResponseBadRequest)

tests/test_views.py:180: AssertionError
----------------------------------------------------------------------------------------- Captured log call -----------------------------------------------------------------------------------------
ERROR    djangosaml2idp.error_views:error_views.py:22 {}
Traceback (most recent call last):
  File "/Users/adammertz/development/farmobile/djangosaml2idp/djangosaml2idp/views.py", line 56, in store_params_in_session
    saml_request = passed_data['SAMLRequest']
KeyError: 'SAMLRequest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adammertz/development/farmobile/djangosaml2idp/djangosaml2idp/views.py", line 73, in sso_entry
    store_params_in_session(request)
  File "/Users/adammertz/development/farmobile/djangosaml2idp/djangosaml2idp/views.py", line 58, in store_params_in_session
    raise ValidationError(_('not a valid SAMLRequest: {}').format(repr(e)))
django.core.exceptions.ValidationError: ["not a valid SAMLRequest: KeyError('SAMLRequest',)"]
___________________________________________________________________ TestIdPHandlerViewMixin.test_set_sp_errors_if_sp_not_defined ____________________________________________________________________

self = <tests.test_views.TestIdPHandlerViewMixin object at 0x10bb516d8>

    def test_set_sp_errors_if_sp_not_defined(self):
        mixin = IdPHandlerViewMixin()
    
        with pytest.raises(ImproperlyConfigured):
>           mixin.set_sp('this_sp_does_not_exist')
E           AttributeError: 'IdPHandlerViewMixin' object has no attribute 'set_sp'

tests/test_views.py:206: AttributeError
______________________________________________________________________ TestIdPHandlerViewMixin.test_set_sp_works_if_sp_defined ______________________________________________________________________

self = <tests.test_views.TestIdPHandlerViewMixin object at 0x10bd99e80>, settings = <pytest_django.fixtures.SettingsWrapper object at 0x10bd994e0>

    def test_set_sp_works_if_sp_defined(self, settings):
        mixin = IdPHandlerViewMixin()
>       mixin.set_sp('test_generic_sp')
E       AttributeError: 'IdPHandlerViewMixin' object has no attribute 'set_sp'

tests/test_views.py:210: AttributeError
__________________________________________________________ TestIdPHandlerViewMixin.test_set_processor_errors_if_processor_cannot_be_loaded __________________________________________________________

self = <tests.test_views.TestIdPHandlerViewMixin object at 0x10bb0dc50>

    def test_set_processor_errors_if_processor_cannot_be_loaded(self):
        mixin = IdPHandlerViewMixin()
>       mixin.set_sp('test_sp_with_bad_processor')
E       AttributeError: 'IdPHandlerViewMixin' object has no attribute 'set_sp'

tests/test_views.py:219: AttributeError
_______________________________________________________________ TestIdPHandlerViewMixin.test_set_processor_defaults_to_base_processor _______________________________________________________________

self = <tests.test_views.TestIdPHandlerViewMixin object at 0x10bc8e0b8>

    def test_set_processor_defaults_to_base_processor(self):
        mixin = IdPHandlerViewMixin()
>       mixin.set_sp('test_sp_with_no_processor')
E       AttributeError: 'IdPHandlerViewMixin' object has no attribute 'set_sp'

tests/test_views.py:226: AttributeError
_________________________________________________________________ TestIdPHandlerViewMixin.test_get_processor_loads_custom_processor _________________________________________________________________

self = <tests.test_views.TestIdPHandlerViewMixin object at 0x10bd1b5c0>

    def test_get_processor_loads_custom_processor(self):
        mixin = IdPHandlerViewMixin()
>       mixin.set_sp('test_sp_with_custom_processor')
E       AttributeError: 'IdPHandlerViewMixin' object has no attribute 'set_sp'

tests/test_views.py:233: AttributeError
__________________________________________________________________________ TestIdPHandlerViewMixin.test_check_access_works __________________________________________________________________________

self = <tests.test_views.TestIdPHandlerViewMixin object at 0x10bc20ac8>

    def test_check_access_works(self):
        mixin = IdPHandlerViewMixin()
>       mixin.set_sp('test_generic_sp')
E       AttributeError: 'IdPHandlerViewMixin' object has no attribute 'set_sp'

tests/test_views.py:250: AttributeError
__________________________________________________________________ TestIdPHandlerViewMixin.test_check_access_fails_when_it_should ___________________________________________________________________

self = <tests.test_views.TestIdPHandlerViewMixin object at 0x10bb5b9b0>

    def test_check_access_fails_when_it_should(self):
        mixin = IdPHandlerViewMixin()
>       mixin.set_sp('test_sp_with_custom_processor_that_doesnt_allow_access')
E       AttributeError: 'IdPHandlerViewMixin' object has no attribute 'set_sp'

tests/test_views.py:256: AttributeError
_________________________________________________________________________ TestIdPHandlerViewMixin.test_build_authn_response _________________________________________________________________________

self = <tests.test_views.TestIdPHandlerViewMixin object at 0x10bae7518>

    def test_build_authn_response(self):
        mixin = IdPHandlerViewMixin()
        try:
>           mixin.dispatch(HttpRequest())

tests/test_views.py:264: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <djangosaml2idp.views.IdPHandlerViewMixin object at 0x10bae7ac8>, request = <HttpRequest>, args = (), kwargs = {}, conf = <saml2.config.IdPConfig object at 0x10bae7080>

    def dispatch(self, request, *args, **kwargs):
        """ Construct IDP server with config from settings dict
        """
        conf = IdPConfig()
        try:
            conf.load(copy.deepcopy(settings.SAML_IDP_CONFIG))
            self.IDP = Server(config=conf)
        except Exception as e:
            return error_cbv.handle_error(request, exception=e)
>       return super().dispatch(request, *args, **kwargs)
E       AttributeError: 'super' object has no attribute 'dispatch'

djangosaml2idp/views.py:95: AttributeError

During handling of the above exception, another exception occurred:

self = <tests.test_views.TestIdPHandlerViewMixin object at 0x10bae7518>

    def test_build_authn_response(self):
        mixin = IdPHandlerViewMixin()
        try:
            mixin.dispatch(HttpRequest())
        except AttributeError:
>           mixin.set_sp('test_generic_sp')
E           AttributeError: 'IdPHandlerViewMixin' object has no attribute 'set_sp'

tests/test_views.py:266: AttributeError
=================================================================================== 15 failed, 34 passed in 4.48s ===================================================================================
```

**Comment by Amertz08** [comment]
It looks like `IdPHandlerViewMixin` most definitely does not have `set_sp` and `dispatch`. 

1. set_sp - Looking through the git history for `views.py` there never appears to be a method `set_sp` ever on the `IdPHandlerViewMixin` unless I missed it.
1. `dispatch` appears to be a method on the base `View` class provided by Django. I believe simply inheriting from `View` would fix this. That being said at that point it wouldn't really be a "Mixin".

**Comment by mhindery** [comment]
With some recent developments and releases, several of the items above are checked off nowadays. For specific requests, please open a separate MR or issue.
